turbot/steampipe-mod-aws-compliance

conformance_pack/codebuild.sp, foundational_security/codebuild.sp, foundational_security/foundational_security.sp, hipaa/164_308_a_1_ii_b.sp, nist_cyber_security_v11/function_de.sp, pci_v321/codebuild.sp, query/codebuild/codebuild_project_source_repo_oauth_configured.sql
**_Check description_**: `CodeBuild GitHub or Bitbucket source repository URLs should use OAuth`
**_Config Rule_**           : [codebuild-project-source-repo-url-check](https://docs.aws.amazon.com/config/latest/developerguide/codebuild-project-source-repo-url-check.html)
**_Frameworks updated_**
```
HIPAA    - 164.308(a)(1)(ii)(B)
FSBP     - CodeBuild.1
PCI DSS  - CodeBuild.1
NIST CSF - DE.AE-5
```
=> Add control check for `codebuild-project-source-repo-url-check`. Closes #239 

conformance_pack/vpc.sp, nist_csf/function_pr.sp, query/vpc/vpc_security_group_associated.sql, query/vpc/vpc_security_group_associated_to_eni.sql
=> vpc_security_group_associated.sql added  with distinct to filter security groups and nist_csf_pr_ds_3 now uses new query. Closes#282

query/iam/iam_user_unused_credentials_45.sql, query/iam/iam_user_unused_credentials_90.sql
=> Update query to show root_account user status as info.

cis_v130/section_1.sp, cis_v140/section_1.sp, foundational_security/iam.sp, query/iam/iam_all_policy_no_star_star.sql, query/iam/iam_custom_policy_no_service_wild_card.sql
1. **`foundational_security_iam_1 `** earlier using `iam_policy_no_star_star.sql` was not valid, as it was not checking attachment, now it will use query `iam_custom_policy_no_star_star.sql`  which is added with attachment check and restricted to customer managed policies.
2. `iam_policy_no_star_star` has occurrences in other compliance mods, hence retaining it as is. `iam_custom_policy_no_star_star.sql` is only used in **iam.sp** file hence safe.
3. **` foundational_security_iam_21`** , now uses new query **`iam_custom_policy_no_service_wild_card.sql `** . Earlier it was using the query `iam_custom_policy_no_star_star.sql`  which was used by `foundational_security_iam_1` (mentioned above). As per **` foundational_security_iam_21`** requirement, control checks for `service:*` pattern. …
=> Update queries to check policy attachment & separation to validate all  vs custom iam policies. Fixes #277 Closes #280

query/backup/backup_plan_min_retention_35_days.sql
```
> with all_plans as (
select
arn,
r as Rules,
title,
region,
account_id
from
aws_backup_plan,
jsonb_array_elements(backup_plan -> 'Rules') as r
)
select
-- Required Columns
-- The resource ARN can be duplicate as we are checking all the associated rules to the backup-plan
-- Backup plans are composed of one or more backup rules.
-- https://docs.aws.amazon.com/aws-backup/latest/devguide/creating-a-backup-plan.html
r.arn as resource,
case
when r.Rules is null then 'alarm'
when r.Rules ->> 'Lifecycle' is null then 'ok'
when (r.Rules -> 'Lifecycle' ->> 'DeleteAfterDays')::int >= 37 then 'ok'
else 'alarm'
end as status,
case
when r.Rules is null then r.title || ' retention period not set.'
when r.Rules ->> 'Lifecycle' is null then (r.Rules ->> 'RuleName') || ' retention period set to never …
```
=> backup_plan_min_retention_35_days needs to handle rules with 'Never expire'. Closes #313

query/dynamodb/dynamodb_table_auto_scaling_enabled.sql
```
> with target_count as (
select
t.resource_id as resource_id,
count(t.resource_id) as count
from
aws_appautoscaling_target as t where service_namespace = 'dynamodb'
group by t.resource_id
)
select
-- Required Columns
d.arn as resource,
case
when t.resource_id is null then 'alarm'
when t.count < 2 then 'alarm'
else 'ok'
end as status,
case
when t.resource_id is null then d.title || ' autoscaling not enabled.'
when t.count < 2 then d.title || ' auto scaling not enabled for both read and write capacity.'
else d.title || ' autoscaling enabled for both read and write capacity.'
end as reason,
-- Additional Dimensions
d.region,
d.account_id
from
aws_dynamodb_table as d
left join target_count as t on concat('table/', d.name) = t.resource_id; …
```
=> DynamoDB table auto scaling should be enabled fails. Closes #31

query/config/config_enabled_all_regions.sql
This is a follow-up of https://github.com/turbot/steampipe-mod-aws-compliance/issues/279 and also fixes https://github.com/turbot/steampipe-mod-aws-compliance/issues/26.
=> feat(aws/cis): fix config query

query/dynamodb/dynamodb_table_auto_scaling_enabled.sql
=> Fix the `dynamodb_table_auto_scaling_enabled` query to correctly check if the tables have on demand capacity enabled closes #349

pci_v321/docs/pci_v321_opensearch.md, pci_v321/docs/pci_v321_opensearch_1.md, pci_v321/docs/pci_v321_opensearch_2.md, pci_v321/opensearch.sp, pci_v321/pci.sp, query/opensearch/opensearch_domain_encryption_at_rest_enabled.sql, query/opensearch/opensearch_domain_in_vpc.sql
=> Add new controls for PCI DSS in Security Hub - PCI.OpenSearch.1 & PCI.OpenSearch.2 Closes #383

query/rds/rds_db_instance_deletion_protection_enabled.sql
```
select
-- Required Columns
arn as resource,
case
when engine like any ( ARRAY['aurora%', 'docdb', 'neptune']) then 'skip'
when deletion_protection then 'ok'
else 'alarm'
end status,
case
when engine like any ( ARRAY['aurora%', 'docdb', 'neptune']) then title || ' is of ' || engine || ' cluster, deletion protection is set at cluster level.'
when deletion_protection then title || ' deletion protection enabled.'
else title || ' deletion protection not enabled.'
end reason,
-- Additional Dimensions
region,
account_id
from
aws_rds_db_instance;
+-------------------------------------------------------------------+--------+-----------------------------------------------------------------------------------------------------+------------+--------------+
| resource …
```
=> Aurora - Deletion protection is at cluster level and not DB instance level - foundational security logic should be updated Closes #400

query/lambda/lambda_function_restrict_public_access.sql
=> lambda_function_restrict_public_access.sql query not evaluating correctly Closes #421

query/vpc/vpc_flow_logs_enabled.sql
- CIS v1.4.0
I started getting the following error with the latest `main` when running `steampipe check`:
```
| + 3.9 Ensure VPC flow logging is enabled in all VPCs .................................................................................. 1 /   1 [=         ]
| |
| | ERROR: control result is missing required column: [resource]
|
```
This PR is an attempt to fix that.
(data has been sanitized to mask real IDs)
```
| + 3.9 Ensure VPC flow logging is enabled in all VPCs .................................................................................. 0 /   1 [=         ]
| | |
| | OK   : VPC_ID flow logging enabled. ................................................................................ us-east-1 0000000000
```
Steampipe version v0.15.0
AWS plugin version v0.68.0
=> Fix error from VPC flow logs query

conformance_pack/cloudtrail.sp
=> Removed the cloudtrail_enabled_all_regions control since it is no longer being used by any benchmark

foundational_security/autoscaling.sp, foundational_security/docs/foundational_security_autoscaling_6.md, query/autoscaling/autoscaling_use_multiple_instance_types_in_multiple_az.sql
=> Add FSBP AutoScaling.6 Closes #472

query/lambda/lambda_function_use_latest_runtime.sql
```
+ 2 Lambda functions should use latest runtimes ..................................................................... 2 / 8 [==========]
| 
ALARM: cloud9-AppTwo-funcone-W408ZRFMCP4Q uses nodejs6.10 which is not the latest version. .................... eu-west-1 533793682495
ALARM: cloud9-TestApp-lambdaone-A71A4OKVLX6D uses nodejs6.10 which is not the latest version. ................. eu-west-1 533793682495
OK   : test1 uses latest runtime - nodejs14.x. ............................................................... ap-south-1 111111111111
OK   : graviton2 uses latest runtime - nodejs14.x. ............................................................ us-east-2 111111111111
OK   : tetest0vpc uses latest runtime - nodejs14.x. ........................................................... …
```
=>  Update foundational_security_lambda_2 control to use latest runtimes Closes #495

foundational_security/docs/foundational_security_s3_12.md, foundational_security/s3.sp, query/s3/s3_bucket_acls_should_prohibit_user_access.sql
=> Add [S3.12] S3 access control lists (ACLs) should not be used to manage user access to buckets. Closes #363

query/ebs/ebs_attached_volume_encryption_enabled.sql
=> ebs_attached_volume_encryption_enabled should validate all EBS volume without where condition Closes #503

query/acm/acm_certificate_expires_30_days.sql
=> ACM certificate expiry Closes #524

query/cloudtrail/cloudtrail_multi_region_trail_enabled.sql
=> CloudTrail Control doesn't acknowledge organization-level trails Closes #536

conformance_pack/lambda.sp
=> Lambda functions should operate in more than one availability zone false positives. Fixes #609

conformance_pack/docdb.sp, conformance_pack/rds.sp, other_checks/other.sp
```sql
> query.rds_db_instance_logging_enabled
+-----------------------------------------------------------------+--------------+--------+------------------------------------------------+-----------+--------------+
| resource                                                        | engine       | status | reason                                         | region    | account_id   |
+-----------------------------------------------------------------+--------------+--------+------------------------------------------------+-----------+--------------+
| arn:aws:rds:us-east-1:123793682495:db:database-1-instance-1     | aurora-mysql | alarm  | database-1-instance-1 logging not enabled.     | us-east-1 | 123793682495 |
| arn:aws:rds:us-east-1:123793682495:db:docdb-2023-06-01-14-12-13 | docdb …
```
=> Add docdb_cluster_instance_logging_enabled control to other checks

conformance_pack/iam.sp
```
madhushreeray ~/turbot/steampipe-mod-aws-compliance [issue-662-reopened] $ steampipe check control.iam_role_unused_60 limit 10
+ IAM roles that have not been used in 60 days should be removed ................................................................................................................ 242 / 282 [==========]
| 
ALARM: AWSCodePipelineServiceRole-us-east-1-testmr was last used 27-Sep-2022 (268 days ago). .................................................................................... aws_aab 111111111111
ALARM: AWSCodePipelineServiceRole-us-east-1-pipeline78 was last used 20-Mar-2023 (94 days ago). ................................................................................. aws_aab 111111111111
ALARM: AWSServiceRoleForKafka was last used 20-Sep-2022 (275 days …
```
=> Update query `iam_role_unused_60` to use the correct resource and common dimension

conformance_pack/rds.sp, pci_dss_v321/requirement_10.sp, pci_dss_v321/requirement_8.sp
Control Added:
Benchmark | Control(s)
-- | --
10_5_5 | cloud_trail_log_file_validation_enabled
8_7_a | rds_instance_iam_authentication_enabled
8_7_b | rds_instance_iam_authentication_enabled
8_7_c | rds_instance_iam_authentication_enabled
8_7_d | rds_instance_iam_authentication_enabled
Controls Removed:
Benchmark | Control(s)
-- | --
8_7_a | rds_db_cluster_iam_authentication_enabled
8_7_b | rds_db_cluster_iam_authentication_enabled
8_7_c | rds_db_cluster_iam_authentication_enabled
8_7_d | rds_db_cluster_iam_authentication_enabled
**Overall Unique Controls Added/Removed**
Only 1 unique control got **replaced**:
**rds_db_cluster_iam_authentication_enabled** > **rds_db_instance_iam_authentication_enabled**
=> Add/Update AWS Audit Manager > PCI DSS V321 controls (2023-07-04). Closes #680

cis_v200/docs/cis_v200_5_1.md, cis_v200/docs/cis_v200_5_2.md, cis_v200/section_5.sp, conformance_pack/acm.sp, conformance_pack/vpc.sp
- docs(typo): Fix TDP => TCP
- docs(acm): Fix title of ACM certificates expiration control
=> docs: fix typos and description

conformance_pack/lambda.sp, foundational_security/docs/foundational_security_lambda_2.md, foundational_security/lambda.sp
This change updates the list of supported AWS lambda runtimes according to the [service documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
=> Update supported lambda runtimes

conformance_pack/lambda.pp
Lambda runtime python3.8 was deprecated on Oct 14, 2024.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-deprecated
=> set lambda python3.8 as deprecated runtime

conformance_pack/iam.pp
Before fix:
```
powerpipe control run iam_user_one_active_key
+ Ensure there is only one active access key available for any single IAM user .......... 1 / 1 [==========]
ERROR: syntax error at or near "," (SQLSTATE 42601)
Summary
OK ...... 0 [          ]
SKIP .... 0 [          ]
INFO .... 0 [          ]
ALARM ... 0 [          ]
ERROR ... 1 [==========]
TOTAL ............. 1 / 1 [==========]
```
After fix:
```
powerpipe control run iam_user_one_active_key
+ Ensure there is only one active access key available for any single IAM user .......... 4 / 35 [==========]
| 
ALARM: arn:aws:iam::333333333333:user/demoraj has 2 active access key(s). ......... 333333333333
ALARM: arn:aws:iam::333333333333:user/karan-popat has 2 active access key(s). ..... 333333333333
ALARM: …
```
=> fix: prevent SQL syntax error from dangling comma when tag_dimension is empty. Closes #894

conformance_pack/account.pp
```
> with alternate_security_contact as (
select
name,
account_id
from
aws_account_alternate_contact
where
contact_type = 'SECURITY'
),
account as (
select
arn,
partition,
title,
account_id,
_ctx
from
aws_account
)
select
arn as resource,
case
when a.partition = 'aws-us-gov' then 'info'
-- Name is a required field if setting a security contact
when c.name is not null then 'ok'
else 'alarm'
end as status,
case
when a.partition = 'aws-us-gov' then a.title || ' in GovCloud, manual verification required.'
when c.name is not null then a.title || ' has security contact ' || c.name || ' registered.'
else a.title || ' security contact not registered.'
end as reason
from
account as a
left join alternate_security_contact as c on  c.account_id = a.account_id;; …
```
=> Fix query account_alternate_contact_security_registered to correctly list all the accounts closes #916
