turbot/steampipe-mod-aws-compliance

README.md
mod.sp

update README and mod.sp for image locations closes #3

---

pci_v321/pci.sp
pci_v321/redshift.sp
query/redshift/redshift_cluster_prohibit_public_access.sql

Add PCI v3.2.1 Redshift benchmark and controls. closes #1

---

pci_v321/es.sp
pci_v321/pci.sp
query/es/es_domain_encryption_at_rest_enabled.sql
query/es/es_domain_in _vpc.sql

Add PCI v3.2.1 ES benchmark and controls. Closes #9

---

pci_v321/pci.sp
pci_v321/s3.sp
query/s3/s3_bucket_restrict_public_read_access.sql
query/s3/s3_bucket_restrict_public_write_access.sql

Add PCI v3.2.1 S3 benchmark and controls. Closes #7

---

pci_v321/pci.sp
pci_v321/rds.sp
query/rds/rds_db_instance_prohibit_public_access.sql
query/rds/rds_snapshot_prohibit_public_access.sql

Add PCI v3.2.1 RDS benchmark and controls. closes #2

---

pci_v321/pci.sp
pci_v321/sagemaker.sp
query/sagemaker/sagemaker_notebook_instance_direct_internet_access_disabled.sql

Add PCI v3.2.1 SageMaker benchmark and controls. closes #15

---

pci_v321/cw.sp
pci_v321/pci.sp

Add PCI v3.2.1 CW benchmark and controls. Closes #21

---

pci_v321/cloudtrail.sp
pci_v321/docs/pci_v321_cloudtrail_3.md
pci_v321/docs/pci_v321_cloudtrail_4.md

Add AWS Security Hub PCI v3.2.1 cloudtrail.3 & 4 docs. Closes #23

---

pci_v321/ec2.sp
query/vpc/vpc_unused_security_group.sql

Add PCI v3.2.1 EC2.3 control. Closes #35

---

pci_v321/codebuild.sp
pci_v321/pci.sp
query/codebuild/codebuild_project_env_variables_with_no_clear_text.sql

Add PCI v3.2.1 CodeBuild benchmark and controls. Closes #40

---

pci_v321/elbv2.sp
pci_v321/pci.sp
query/ec2/ec2_application_lb_configured_to_redirect_http_request_to_https.sql

Add PCI v3.2.1 ELBV2 benchmark and controls. Closes #47

---

pci_v321/guardduty.sp
pci_v321/pci.sp
query/guardduty/guardduty_enabled.sql

Add PCI v3.2.1 GuardDuty benchmark and controls. Closes #49

---

pci_v321/docs/pci_v321_es.md
pci_v321/docs/pci_v321_es_1.md
pci_v321/docs/pci_v321_es_2.md
pci_v321/docs/pci_v321_kms.md
pci_v321/docs/pci_v321_kms_1.md
pci_v321/docs/pci_v321_lambda.md
pci_v321/docs/pci_v321_lambda_1.md
pci_v321/docs/pci_v321_lambda_2.md
pci_v321/docs/pci_v321_sagemaker.md
pci_v321/docs/pci_v321_sagemaker_1.md
pci_v321/es.sp
pci_v321/kms.sp
pci_v321/lambda.sp
pci_v321/sagemaker.sp

Add AWS PCI Elasticsearch, Lamda, KMS, Sagemaker docs. Closes #59

---

pci_v321/docs/pci_v321_iam.md
pci_v321/docs/pci_v321_iam_1.md
pci_v321/docs/pci_v321_iam_2.md
pci_v321/docs/pci_v321_iam_3.md
pci_v321/docs/pci_v321_iam_4.md
pci_v321/docs/pci_v321_iam_5.md
pci_v321/iam.sp

Add AWS PCI IAM Docs. Closes #62

---

pci_v321/dms.sp
pci_v321/docs/pci_v321_dms.md
pci_v321/docs/pci_v321_dms_1.md
pci_v321/docs/pci_v321_rds.md
pci_v321/docs/pci_v321_rds_1.md
pci_v321/docs/pci_v321_rds_2.md
pci_v321/docs/pci_v321_redshift.md
pci_v321/docs/pci_v321_redshift_1.md
pci_v321/rds.sp
pci_v321/redshift.sp

Add AWS PCI DMS, RDS, Redshift Docs. Closes #63

---

pci_v321/docs/pci_v321_s3.md
pci_v321/docs/pci_v321_s3_1.md
pci_v321/docs/pci_v321_s3_2.md
pci_v321/docs/pci_v321_s3_3.md
pci_v321/docs/pci_v321_s3_4.md
pci_v321/docs/pci_v321_s3_5.md
pci_v321/docs/pci_v321_s3_6.md
pci_v321/s3.sp

Add AWS PCI S3 Docs. Closes #64

---

pci_v321/cw.sp
pci_v321/docs/pci_v321_cw.md
pci_v321/docs/pci_v321_cw_1.md
pci_v321/docs/pci_v321_guardduty.md
pci_v321/docs/pci_v321_guardduty_1.md
pci_v321/docs/pci_v321_ssm.md
pci_v321/docs/pci_v321_ssm_1.md
pci_v321/docs/pci_v321_ssm_2.md
pci_v321/docs/pci_v321_ssm_3.md

Add AWS PCI SSM, CW, GuardDuty Docs. Closes #68

---

pci_v321/autoscaling.sp
pci_v321/config.sp
pci_v321/docs/pci_v321_autoscaling.md
pci_v321/docs/pci_v321_autoscaling_1.md
pci_v321/docs/pci_v321_codebuild.md
pci_v321/docs/pci_v321_codebuild_1.md
pci_v321/docs/pci_v321_codebuild_2.md
pci_v321/docs/pci_v321_config.md
pci_v321/docs/pci_v321_config_1.md

Add AWS > PCI > Autoscaling, CodeBuild & Config docs. Closes #51

---

foundational_security/foundational_security.sp
foundational_security/lambda.sp
query/lambda/lambda_function_should_use_latest_runtime.sql
query/lambda/lambda_function_use_latest_runtime.sql

Add AWS Foundational Security Best Practices Lambda benchmark. Closes #75

---

cis_v140/docs/cis_v140_2_1_3.md
cis_v140/docs/cis_v140_2_3.md
cis_v140/docs/cis_v140_2_3_1.md
cis_v140/section_2.sp

Add CIS 1.4.0 section 2.1.3 and 2.3.1 docs. Closes #97

---

hipaa/164_308_a_3_ii_A.sp
hipaa/hipaa.sp

Add HIPAA controls 164_308_a_3_ii_A

---

hipaa/164_312_e_2_ii.sp

Added hipaa_164_312_e_2_ii benchmark and control

---

hipaa/164_312_e_1.sp
hipaa/hipaa.sp
query/ec2/ec2_instance_in_vpc.sql
query/vpc/vpc_security_group_authorized_port.sql
query/vpc/vpc_security_group_no_ingress_tcp_udp_all.sql

Add checks for HIPAA 164.312(e)(1)

---

hipaa/164_312_e_2_i.sp
hipaa/hipaa.sp

Add HIPAA controls 164_312_e_2_i

---

hipaa/164_308_a_1_ii_b.sp
hipaa/164_312_e_1.sp
query/vpc/vpc_internet_gw_attached_to_authorized_vpc.sql
query/vpc/vpc_security_group_open_to_authorized_port.sql
query/vpc/vpc_security_group_restrict_common_port.sql
query/vpc/vpc_security_group_restrict_ssh.sql

Add control for hipaa 164_308_a_1_ii_b benchmark

---

cis_v130/section_1.sp
cis_v140/section_1.sp
foundational_security/iam.sp
hipaa/164_308_a_3_ii_a.sp
hipaa/164_312_d.sp
hipaa/hipaa.sp
pci_v321/iam.sp
query/iam/iam_user_console_access_mfa_enabled.sql
query/iam/iam_user_mfa_enabled.sql

Add hipaa_164_312_d benchmark and controls

---

hipaa/164_308_a_1_ii_d.sp
hipaa/164_308_a_3_ii_a.sp
hipaa/164_308_a_6_i.sp
hipaa/164_308_a_6_ii.sp
hipaa/164_312_b.sp
hipaa/164_312_e_2_i.sp
query/cloudtrail/cloudtrail_multi_region_trail_enabled.sql
query/lambda/lambda_function_dead_letter_queue_configured.sql

Add checks for multi-region-cloudtrail-enabled and lambda-dlq-check. Closes #196

---

query/elb/elb_application_waf_enabled.sql
rbi/annex_i_5_1.sp
rbi/rbi.sp

Add checks for RBI AnnexI(5.1)

---

query/cloudwatch/cloudwatch_log_group_retention_period_365.sql
rbi/annex_i_7_4.sp
rbi/rbi.sp

Add checks for RBI AnnexI(7.4)

---

rbi/annex_i_12.sp
rbi/annex_i_1_1.sp
rbi/rbi.sp

Add checks for RBI AnnexI(12)

---

conformance_pack/guardduty.sp
conformance_pack/sagemaker.sp
conformance_pack/vpc.sp
hipaa/164_308_a_1_ii_b.sp
hipaa/164_308_a_6_ii.sp
hipaa/164_308_a_7_i.sp
hipaa/164_312_a_2_iv.sp
hipaa/164_312_e_2_ii.sp
query/guardduty/guardduty_finding_archived.sql
query/sagemaker/sagemaker_endpoint_configuration_encryption_at_rest_enabled.sql
query/vpc/vpc_vpn_tunnel_up.sql

**_Added checks_**
- vpc-vpn-2-tunnels-up
- sagemaker-endpoint-configuration-kms-key-configured
- guardduty-non-archived-findings

Add checks for HIPAA controls

---

hipaa/164_308_a_3_ii_a.sp
hipaa/164_308_a_3_ii_b.sp
hipaa/164_308_a_3_ii_c.sp
hipaa/164_308_a_4_i.sp
hipaa/164_308_a_4_ii_b.sp
hipaa/164_308_a_4_ii_c.sp
hipaa/164_308_a_6_i.sp
hipaa/164_308_a_6_ii.sp
hipaa/164_308_a_7_i.sp
hipaa/164_308_a_7_ii_a.sp
hipaa/164_312_a_1.sp
hipaa/164_312_a_2_i.sp
hipaa/164_312_a_2_ii.sp
hipaa/164_312_a_2_iv.sp
hipaa/164_312_b.sp
hipaa/164_312_c_1.sp
hipaa/164_312_c_2.sp
hipaa/164_312_d.sp
hipaa/164_312_e_1.sp
hipaa/164_312_e_2_i.sp
hipaa/164_312_e_2_ii.sp

Update HIPAA benchmark tags structure. Closes  #227

---

README.md

Update README. Closes #231

---

conformance_pack/dynamodb.sp
conformance_pack/ebs.sp
conformance_pack/efs.sp
conformance_pack/rds.sp
query/dynamodb/dynamodb_table_in_backup_plan.sql
query/ebs/ebs_volume_in_backup_plan.sql
query/rds/rds_db_instance_in_backup_plan.sql
rbi_cyber_security/annex_i_12.sp

*_**Added**_*
- dynamodb_in_backup_plan
- ebs_in_backup_plan
- efs_in_backup_plan
- rds_in_backup_plan

Add new control check for RBI benchmark AnnexI (12). Closes #229

---

query/cloudtrail/cloudtrail_multi_region_trail_enabled.sql
query/cloudtrail/cloudtrail_s3_logging_enabled.sql
query/cloudtrail/cloudtrail_trail_integrated_with_logs.sql
query/cloudtrail/cloudtrail_trail_logs_encrypted_with_kms_cmk.sql
query/cloudtrail/cloudtrail_trail_validation_enabled.sql
query/cloudwatch/log_metric_filter_bucket_policy.sql
query/cloudwatch/log_metric_filter_cloudtrail_configuration.sql
query/cloudwatch/log_metric_filter_config_configuration.sql
query/cloudwatch/log_metric_filter_console_authentication_failure.sql
query/cloudwatch/log_metric_filter_console_login_mfa.sql
query/cloudwatch/log_metric_filter_disable_or_delete_cmk.sql
query/cloudwatch/log_metric_filter_iam_policy.sql
query/cloudwatch/log_metric_filter_network_acl.sql
query/cloudwatch/log_metric_filter_network_gateway.sql
query/cloudwatch/log_metric_filter_organization.sql
query/cloudwatch/log_metric_filter_root_login.sql
query/cloudwatch/log_metric_filter_route_table.sql
query/cloudwatch/log_metric_filter_security_group.sql
query/cloudwatch/log_metric_filter_unauthorized_api.sql
query/cloudwatch/log_metric_filter_vpc.sql
query/config/config_enabled_all_regions.sql
query/lambda/lambda_function_use_latest_runtime.sql
query/s3/s3_public_access_block_bucket_account.sql

Query updates for bugs found when testing multi-account connections

---

query/cloudfront/cloudfront_distribution_encryption_in_transit_enabled.sql
query/cloudtrail/cloudtrail_s3_logging_enabled.sql
query/guardduty/guardduty_enabled.sql
query/s3/s3_bucket_cross_region_replication_enabled.sql
query/s3/s3_bucket_restrict_public_read_access.sql
query/s3/s3_bucket_restrict_public_write_access.sql
query/vpc/vpc_igw_attached_to_authorized_vpc.sql

Fix queries with unnecessary quotes (""). Fixes #248

---

CHANGELOG.md

Add CHANGELOG for v0.11 closes #255

---

CHANGELOG.md

Add CHANGELOG for v0.12 closes #261

---

foundational_security/elasticbeanstalk.sp
query/elasticbeanstalk/elastic_beanstalk_enhanced_health_reporting_enabled.sql

Failure in running the elastic_beanstalk_enhanced_health_reporting_enabled query closes #269

---

query/cloudwatch/log_metric_filter_root_login.sql

Update root login filter pattern Closes #284

---

README.md

Update GitHub repo URL link in README.md

---

query/cloudwatch/log_metric_filter_organization.sql

Re-raising the PR since it was closed during the v0.13 release version of the mod. Reference to the original PR - https://github.com/turbot/steampipe-mod-aws-compliance/pull/271

Fix filter query for log_metric_filter_organization

---

conformance_pack/backup.sp
conformance_pack/cloudwatch.sp
conformance_pack/config.sp
conformance_pack/dynamodb.sp
conformance_pack/ebs.sp
conformance_pack/ec2.sp
conformance_pack/efs.sp
conformance_pack/eks.sp
conformance_pack/elb.sp
conformance_pack/fsx.sp
conformance_pack/lambda.sp
conformance_pack/rds.sp
conformance_pack/redshift.sp
conformance_pack/s3.sp
conformance_pack/vpc.sp
conformance_pack/wafv2.sp
nist_csf/function_de.sp
nist_csf/function_id.sp
nist_csf/function_pr.sp
nist_csf/function_rc.sp
nist_csf/function_rs.sp
nist_csf/nist_csf.sp
query/eks/eks_cluster_endpoint_restrict_public_access.sql

Add new benchmarks and controls in NIST CSF. Closes #326

---

docs/index.md
mod.sp

Related to https://github.com/turbot/steampipe-mod-aws-compliance/pull/316

Typo: Audit Manger => Audit Manager

---

CHANGELOG.md

Update CHANGELOG for v0.22

---

mod.sp
query/vpc/vpc_security_group_allows_ingress_authorized_ports.sql
query/vpc/vpc_security_group_remote_administration.sql
query/vpc/vpc_security_group_restrict_ingress_common_ports_all.sql
query/vpc/vpc_security_group_restrict_ingress_ssh_all.sql
query/vpc/vpc_security_group_restrict_ingress_tcp_udp_all.sql
query/vpc/vpc_security_group_restricted_common_ports.sql

Update aws_vpc_security_group_rule table queries to use new columns

---

query/guardduty/guardduty_enabled.sql

Split GuardDuty Checks for Foundational Security into Standard GuardDuty Enabled and S3 Logging Enabled Closes #357

---

foundational_security/cloudfront.sp
foundational_security/docs/foundational_security_cloudfront_9.md
foundational_security/docs/foundational_security_ecr.md
foundational_security/docs/foundational_security_ecr_3.md
foundational_security/docs/foundational_security_elb_10.md
foundational_security/docs/foundational_security_s3_11.md
foundational_security/ecr.sp
foundational_security/elb.sp
foundational_security/foundational_security.sp
foundational_security/s3.sp
query/cloudfront/cloudfront_distribution_custom_origins_encryption_in_transit_enabled.sql
query/ecr/ecr_repository_lifecycle_policy_configured.sql
query/elb/elb_classic_lb_multiple_az_configured.sql
query/s3/s3_bucket_event_notifications_enabled.sql

Added below controls:
- [CloudFront.9] CloudFront distributions should encrypt traffic to custom origins
-  [ECR.3] ECR repositories should have at least one lifecycle policy configured
- [ELB.10] Classic Load Balancer should span multiple Availability Zones
-  [S3.11] S3 Buckets should have event notifications enabled

Add new FSBP controls #358

---

query/opensearch/opensearch_domain_in_vpc.sql

Fix edge case in PCI.OpenSearch.1 query. Closes #386

---

mod.sp

Update AWS plugin dependency from `v0.54.0` to `v0.59.0`

---

query/lambda/lambda_function_multiple_az_configured.sql
query/lambda/lambda_function_use_latest_runtime.sql

Update Lambda queries

---

foundational_security/s3.sp

FSBP Control: 9 S3 bucket server access logging should be enabled referencing wrong query Closes #402

---

query/lambda/lambda_function_restrict_public_access.sql

Fix `Prinipal` typo in lambda_function_restrict_public_access query closes #410

---

CHANGELOG.md

Add CHANGELOG for v0.35

---

query/backup/backup_plan_min_retention_35_days.sql

Update DeleteAfterDays to >= 35 in backup_plan_min_retention_35_days.sql Closes #423

---

CHANGELOG.md

Add CHANGELOG for v0.36

---

CHANGELOG.md

Add CHANGELOG for v0.37

---

conformance_pack/iam.sp
query/iam/iam_inline_policy_blocked_kms_actions.sql
query/iam/iam_policy_inline_no_blocked_kms_actions.sql

Add control for iam_inline_policy_blocked_kms_actions

---

conformance_pack/cloudformation.sp
conformance_pack/cloudfront.sp
conformance_pack/ec2.sp

This PR includes updates for the following services -
- CloudFront
- CloudFormation
- EC2

Update control titles of other compliance checks benchmark

---

query/vpc/vpc_flow_logs_enabled.sql

AWS CIS 1.4 Control 3.9 >> issue with shared VPCs Closes #441

---

CHANGELOG.md

Add CHANGELOG for v0.38

---

query/vpc/vpc_flow_logs_enabled.sql

Update query vpc_flow_logs_enabled

---

query/vpc/vpc_flow_logs_enabled.sql

Fix vpc_flow_logs_enabled query to remove duplicate results

---

CHANGELOG.md

Update CHANGELOG for v0.39

---

query/kms/kms_cmk_rotation_enabled.sql

Reopening https://github.com/turbot/steampipe-mod-aws-compliance/pull/462 as requested. See old PR for details.

Ignore KMS keys that are pending deletion or disabled in rotation check

---

mod.sp

Update dependent AWS plugin version to v0.71.0

---

CHANGELOG.md

Add CHANGELOG for v0.41

---

foundational_security/ec2.sp

Add foundational_security_ec2_27 control to the foundational_security_ec2 benchmark

---

CHANGELOG.md

Add CHANGELOG for v0.42

---

CHANGELOG.md

Add CHANGELOG for v0.44

---

CHANGELOG.md

Add CHANGELOG for v0.45

---

nist_800_53_rev_5/si.sp

Spelling fix

---

query/ecr/ecr_repository_prohibit_public_access.sql

ecr_repository_prohibit_public_access triggers on non-public repositories Closes #512

---

query/cloudwatch/cloudwatch_alarm_action_enabled.sql

Update aws_cloudwatch_alarm query as per aws-sdk-go-v2

---

CHANGELOG.md

Add CHANGELOG for v0.51

---

query/iam/iam_user_in_group.sql
query/vpc/vpc_default_security_group_restricts_all_traffic.sql

Should be released after https://github.com/turbot/steampipe-plugin-aws/pull/1376

Update queries for v2 migration column compatibilty transform removal changes

---

CHANGELOG.md

Add CHANGELOG for v0.53

---

CHANGELOG.md

Add CHANGELOG for v0.54

---

mod.sp

Update aws plugin dependency to v0.92.0 plugin version

---

CHANGELOG.md

Add CHANGELOG for v0.55

---

query/ssm/ec2_instance_ssm_managed.sql

EC2 instances should be managed by AWS Systems Manager Closes #540

---

query/guardduty/guardduty_enabled.sql

GuardDuty should be enabled reports false positive finding when Delegated Admin is in use Closes #537

---

CHANGELOG.md

Add CHANGELOG for v0.56

---

foundational_security/docs/foundational_security_ecr_2.md

Update doc foundational_security_ecr_2.md

---

query/s3/s3_public_access_block_account.sql

Fix typo in the query reason closes #572

---

query/s3/s3_bucket_acls_should_prohibit_user_access.sql

S3 access control lists (ACLs) should not be used to manage user access to buckets Closes #539

---

query/s3/s3_bucket_restrict_public_read_access.sql
query/s3/s3_bucket_restrict_public_write_access.sql

Update s3_bucket_restrict_* queries to check if buckets prohibit public read access  Closes #538

---

mod.sp

Update aws plugin dependency from v0.92.0 to v0.95.0

---

CHANGELOG.md

Add CHANGELOG for v0.58

---

CHANGELOG.md

Update CHANGELOG for v0.61

---

conformance_pack/apigateway.sp
conformance_pack/cloudwatch.sp
conformance_pack/codebuild.sp
conformance_pack/dms.sp
conformance_pack/ebs.sp
conformance_pack/ec2.sp
conformance_pack/efs.sp
conformance_pack/elb.sp
conformance_pack/iam.sp
conformance_pack/kms.sp
conformance_pack/lambda.sp
conformance_pack/networkfirewall.sp
conformance_pack/rds.sp
conformance_pack/s3.sp
conformance_pack/sns.sp
conformance_pack/vpc.sp

Remove extra spaces from queries

---

CHANGELOG.md

Add CHANGELOG for v0.63

---

CHANGELOG.md

Add CHANGELOG for v0.64

---

README.md
docs/index.md

Update index.md and README.md files to use http instead of https

---

CHANGELOG.md

Add CHANGELOG for v0.66

---

CHANGELOG.md
conformance_pack/vpc.sp
foundational_security/ec2.sp
other_checks/other.sp

Move untagged controls to Other checks benchmark

---

conformance_pack/wafv2.sp

wafv2_web_acl_rule_attached fails with ERROR: more than one row returned by a subquery used as an expression (SQLSTATE 21000) closes #644

---

conformance_pack/iam.sp

Update iam_policy_all_attached_no_star_star query to skip AWS managed policies closes #642

---

CHANGELOG.md

Add CHANGELOG for v0.68

---

conformance_pack/kms.sp
hipaa_security_rule_2003/164_308/164_308_a_1_ii_d.sp
hipaa_security_rule_2003/164_312/164_312_a_2_iv.sp
other_checks/other.sp

Add/Update AWS Audit Manager > HIPAA Security Rule 2003 controls. Closes #653

---

nist_800_171_rev_2/ia.sp

Add/Update AWS Audit Manager > NIST_800_171_REV_2 controls (2023-06-05). Closes #648

---

gxp_21_cfr_part_11/11_10.sp

Add/Update AWS Audit Manager > GxP 21 CFR Part 11 controls (2023-06-05). Closes #646

---

conformance_pack/rds.sp

Filter DocumentDB instances from query rds_db_instance_logging_enabled

---

CHANGELOG.md

Add CHANGELOG for v0.69

---

CHANGELOG.md

Add CHANGELOG for v0.70

---

CHANGELOG.md

Add CHANGELOG for v0.71

---

CHANGELOG.md

Add CHANGELOG for v0.72

---

CHANGELOG.md

Add CHANGELOG for v0.73

---

CHANGELOG.md

Add CHANGELOG for v0.74

---

cis_v200/docs/cis_v200_1_1.md
cis_v200/docs/cis_v200_1_4.md
cis_v200/docs/cis_v200_1_7.md
cis_v200/docs/cis_v200_2_1_1.md
cis_v200/docs/cis_v200_2_2_1.md
cis_v200/docs/cis_v200_2_4_1.md
cis_v200/docs/cis_v200_3_6.md

Fix doc formatting - Control: 2.1.1

---

CHANGELOG.md

Add CHANGELOG for v0.75

---

foundational_security/elasticache.sp

Fix typo in the title of the `foundational_security_elasticache` benchmark

---

CHANGELOG.md

Add CHANGELOG for v0.76

---

conformance_pack/lambda.sp
foundational_security/docs/foundational_security_lambda_2.md
foundational_security/lambda.sp

Haven't created an issue yet, but happy to if it needs it for the check

fixlambda_runtime(sign): Update lambda runtimes to match current AWS guidelines

---

CHANGELOG.md

Add CHANGELOG for v0.77

---

CHANGELOG.md

Update CHANGELOG for v0.77

---

audit_manager_control_tower/disallow_instances.sp
audit_manager_control_tower/disallow_internet_connection.sp
audit_manager_control_tower/disallow_public_access.sp
audit_manager_control_tower/ebs_checks.sp
audit_manager_control_tower/multi_factor_authentication.sp
conformance_pack/ebs.sp
conformance_pack/rds.sp

Unique controls added:
- rds_db_instance_encryption_at_rest_enabled
- ebs_volume_unused
Unique controls removed:
- ebs_attached_volume_delete_on_termination_enabled
- rds_db_snapshot_encrypted_at_rest

Add/Update AWS Audit Manager > Control Tower controls. Closes #694

---

CHANGELOG.md

Add CHANGELOG for v0.78

---

CHANGELOG.md

Add CHANGELOG for v0.79

---

conformance_pack/glue.sp

Fix ERROR: control result is missing required column: [resource] for glue controls closes #714

---

all_controls/athena.sp
all_controls/iam.sp
conformance_pack/athena.sp
conformance_pack/iam.sp

Add/Update monthly controls [Oct 23]. Closes #711

---

CHANGELOG.md

Add CHANGELOG for v0.81

---

mod.sp

Update mod.sp to address deprecation warning closes #725

---

CHANGELOG.md

Add CHANGELOG for v0.82

---

CHANGELOG.md

Add CHANGELOG for v0.84

---

all_controls/iam.sp
cisa_cyber_essentials/your_surroundings.sp
cisa_cyber_essentials/your_systems.sp
conformance_pack/iam.sp
ffiec/d_3/d_3_pc.sp
gdpr/article_25.sp

IAM.sp contains redundant controls closes #738

---

foundational_security/secretsmanager.sp

FALSE-Negative and False-Positive for AWS Compliance > Remove unused Secrets Manager secrets closes #751

---

CHANGELOG.md

Add CHANGELOG for v0.86

---

README.md

Add v3.0.0 reference

---

conformance_pack/ssm.sp

False positive: aws_compliance.control.foundational_security_ssm_2 if Patch is not applicable closes #759

---

CHANGELOG.md

Add CHANGELOG for v0.88

---

foundational_security/codebuild.sp
foundational_security/ec2.sp
foundational_security/emr.sp
foundational_security/es.sp
foundational_security/lambda.sp
foundational_security/opensearch.sp
foundational_security/rds.sp
foundational_security/waf.sp

Update foundational_security control titles closes #760

---

mod.sp

Update aws plugin dependency from v0.131.0 to v0.132.0

---

CHANGELOG.md

Add CHANGELOG for v0.89

---

conformance_pack/secretsmanager.sp

Update duplicate titles for AWS Compliance Controls closes #782

---

CHANGELOG.md

Add CHANGELOG for v0.92

---

CHANGELOG.md

Update CHANGELOG for v0.92 release

---

conformance_pack/ecr.sp

Fix query ecr_repository_image_scan_on_push_enabled

---

conformance_pack/lambda.sp
steampipe.spvars.example

Add runtime variable support for control `lambda_function_use_latest_runtime`

---

CHANGELOG.md

Add CHANGELOG for v0.93

---

CHANGELOG.md

Update CHANGELOG for AWS Compliance v0.93

---

CHANGELOG.md

Add CHANGELOG for v0.94

---

conformance_pack/cloudwatch.sp

Optimize log_group_metric_* queries for faster execution and to minimize API usage

---

CHANGELOG.md

Add CHANGELOG for v0.95

---

CHANGELOG.md
README.md
docs/index.md

Add CHANGELOG for v0.96

---

CHANGELOG.md

Add CHANGELOG for v0.98

---

README.md
docs/index.md

Update README.md and index.md files with the new benchmark reference

---

cis_compute_service_v100/docs/cis_compute_service_v100_4_6.md
cis_v130/docs/cis_v130_1_18.md
cis_v140/docs/cis_v140_1_18.md
cis_v150/docs/cis_v150_1_18.md

This PR removes all of the _duplicated_ "the"s.

docs: remove duplicated 'the'

---

conformance_pack/elb.pp

Fixed `elb_application_lb_waf_enabled` query to correctly evaluate results when WAF is enabled or disabled

---

conformance_pack/iam.pp
conformance_pack/organization.pp
conformance_pack/pca.pp
conformance_pack/route53.pp
conformance_pack/vpc.pp
conformance_pack/waf.pp

Refactor queries to use global dimension qualifiers for IAM and Route 53 checks closes #847

---

conformance_pack/vpc.pp

Update resource id to arn for aws_vpc_peering_connection queries

---

all_controls/organization.pp
cis_compute_service_v100/section_2.pp
conformance_pack/organization.pp

Fix service name to use plural form "AWS/Organizations" in multiple files

---

conformance_pack/eks.pp

Refactor EKS secrets encryption query to improve clarity and add version checks closes #870

---

conformance_pack/guardduty.pp
mod.pp

Refactor GuardDuty queries to improve clarity and accuracy of resource identification and status reporting

---

conformance_pack/sagemaker.pp

fix: correct CASE logic for SageMaker notebook encryption at rest reason

---

conformance_pack/cloudtrail.pp

Update reason for control cloudtrail_multi_region_read_write_enabled

---

conformance_pack/config.pp
conformance_pack/iam.pp
conformance_pack/securityhub.pp

Update Security Hub, Config and IAM Access Analyzer queries to respect the regions in aws.spc closes#907

---

conformance_pack/iam.pp

Access Key Rotation Scan Should Exclude Inactive Keys closes #909

---

mod.pp
variables.pp

Add database variable

---

all_controls/ec2.pp
cis_v120/section_1.pp
cis_v130/section_1.pp
cis_v140/section_1.pp
cis_v150/section_1.pp
cis_v200/section_1.pp
cis_v300/section_1.pp
cis_v400/section_1.pp
cis_v500/section_1.pp
conformance_pack/backup.pp
conformance_pack/cloudwatch.pp
conformance_pack/ec2.pp
conformance_pack/eks.pp
conformance_pack/guardduty.pp
conformance_pack/iam.pp
conformance_pack/kms.pp
conformance_pack/s3.pp
conformance_pack/vpc.pp

Update Benchmark: CIS v5.0.0

---

conformance_pack/iam.pp

Incorrect Query - IAM Conformance Pack - KMS Access closes #937
